import Head from 'next/head'
import Header from './components/Header'
import Sidebar from './components/Sidebar'


export default function Home() {
  return (
    <div className='flex flex-row bg-slate-50'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
        {/* <Header /> */}
      <Sidebar />
     <Header />
    </div>
  )
}
