import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Index from "../Layouts/Index";
import { useStateContext } from "../context/contextProvider";
export default function Home() {
  const { activeMenu } = useStateContext();
  return (
    <>
      <Head>
        <title>Next-Sidebar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row flex-wrap overflow-hidden min-h-screen w-full">
        {activeMenu ? (
          <div className="relative w-64 float-left">
            <Sidebar />
          </div>
        ) : (
          <div className="relative w-0"></div>
        )}
        <div
          className="relative float-left 
        overflow-hidden h-10 flex-1"
        >
          <Header />
        </div>
      </div>
    </>
  );
}
